name: Check

on:
    workflow_call:

    workflow_dispatch:

    push:
      branches:
      - "**"

    schedule:
      - cron: "0/10 * * * *" # Runs every 10 minutes

jobs:
    run:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Code
          uses: actions/checkout@v4

        - name: Checkout Resource
          uses: actions/checkout@v4
          with:
            repository: MaaAssistantArknights/MaaResource
            path: res

        - name: Setup Python
          uses: actions/setup-python@v5
          with:
            python-version: "3.12"

        - name: Install Deps
          run: |
            pip install -r requirements.txt

        - name: Run check
          run: |
            python index.py --check --token ${{ secrets.GITHUB_TOKEN }}
            python index.py --check_res --token ${{ secrets.GITHUB_TOKEN }}

        - name: Run Issue (MAA)
          if: env.maa == 'true'
          run: |
            python index.py --issue --token ${{ secrets.ISSUE_TOKEN }}

        - name: Run Issue (Resource)
          if: env.res == 'true'
          run: |
            mv res/resource/version.json .
            python index.py --issue_res --token ${{ secrets.ISSUE_TOKEN }}

        - name: Commit Version (MAA)
          if: env.maa == 'true'
          uses: EndBug/add-and-commit@v9
          with:
            add: |
              version
            message: "[MAA UPDATE] ${{ env.ver }}"
            default_author: github_actions
            committer_name: GitHub Actions
            committer_email: 41898282+github-actions[bot]@users.noreply.github.com

        - name: Commit Version (Resource)
          if: env.res == 'true'
          uses: EndBug/add-and-commit@v9
          with:
            add: |
              version.json
            message: "[RES UPDATE] ${{ env.res_ver }}"
            default_author: github_actions
            committer_name: GitHub Actions
            committer_email: 41898282+github-actions[bot]@users.noreply.github.com
