name: Check_Login

on:
    workflow_call:
      secrets:
          API_TOKEN_GITHUB:
            required: true
          ALI_TOKEN:
            required: true
    workflow_dispatch:

jobs:
    run:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Code
          uses: actions/checkout@v4

        - name: Checkout Secret
          uses: actions/checkout@v4
          with:
            repository: "weinibuliu/Maa-Mirror-Secret"
            token: ${{ secrets.API_TOKEN_GITHUB }}
            path: secret

        - name: Setup Python
          uses: actions/setup-python@v5
          with:
            python-version: "3.12"

        - name: Install Deps
          run: |
            pip install -r requirements.txt

        - name: Run Check
          timeout-minutes: 5
          run: |
            mv -f secret/.bypy .bypy
            mv -f .bypy /home/runner/.bypy
            sudo chmod 755 /home/runner/.bypy
            python index.py --check_login --ali ${{ secrets.ALI_TOKEN }}
            mv -f /home/runner/.bypy .bypy