name: Meta

on:
    workflow_dispatch:

    push:
      branches:
      - "**"

    schedule:
      - cron: "0/20 * * * *" # Runs every 20 minutes

jobs:
  Update:
    uses: ./.github/workflows/Update.yml
    secrets:
      API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      ALI_TOKEN: ${{ secrets.ALI_TOKEN }}

  Login:
    uses: ./.github/workflows/Login.yml
    secrets:
      API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      ALI_TOKEN: ${{ secrets.ALI_TOKEN }}
