name: Update

on:
    workflow_call:
        secrets:
            API_TOKEN_GITHUB:
              required: true
            ALI_TOKEN:
              required: true

        inputs:
          ver:
            type: string
            required: true

    workflow_dispatch:

jobs:
    run:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Code
          uses: actions/checkout@v4

        - name: Checkout Secret
          uses: actions/checkout@v4
          with:
            repository: "weinibuliu/Maa-Mirror-Secret"
            token: ${{ secrets.API_TOKEN_GITHUB }}
            path: secret

        - name: Download Release
          uses: robinraju/release-downloader@v1
          with:
            repository: "MaaAssistantArknights/MaaAssistantArknights"
            tag: ${{ inputs.ver }}
            out-file-path: "."
            fileName: "*"
            zipBall: true
            token: ${{ secrets.GITHUB_TOKEN }}

        - name: Setup Python
          uses: actions/setup-python@v5
          with:
            python-version: "3.12"

        - name: Install Deps
          run: |
            pip install -r requirements.txt
            sudo apt-get install p7zip-full

        - name: Zip File
          run: |
            7z a -sfx MAA-${{ inputs.ver }}-win-x64.exe MAA-${{ inputs.ver }}-win-x64.zip

        - name: Run Upload
          timeout-minutes: 60
          run: |
            mv -f secret/.bypy .bypy
            mv -f .bypy /home/runner/.bypy
            sudo chmod 755 /home/runner/.bypy
            python index.py --upload --ali ${{ secrets.ALI_TOKEN }}
            mv -f /home/runner/.bypy .bypy

        - name: Run Issue
          run: |
            python index.py --issue --token ${{ secrets.API_TOKEN_GITHUB }}

        - name: Commit Version
          uses: EndBug/add-and-commit@v9
          with:
            add: |
              version
            message: "[UPDATE] ${{ inputs.ver }}"
            default_author: github_actions
            committer_name: GitHub Actions
            committer_email: 41898282+github-actions[bot]@users.noreply.github.com