name: Update

on:
    push:
      branches:
      - "**"

    schedule:
      - cron: "0 */1 * * *" # Runs every hour

jobs:
    Build:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Code
          uses: actions/checkout@v4

        - name: Setup Python
          uses: actions/setup-python@v5
          with:
            python-version: "3.12"

        - name: Install Deps
          run: |
            pip install -r requirements.txt

        - name: Run check
          run: |
            python index.py --check --token ${{ secrets.GITHUB_TOKEN }}

      outputs:
        update: ${{ env.update }}
        ver: ${{ env.update_ver }}

    Update:
      runs-on: ubuntu-latest
      needs: [Build]
      if: needs.Build.outputs.update == 'true'
      steps:
        - name: Checkout Code
          uses: actions/checkout@v4

        - name: Checkout Secret
          uses: actions/checkout@v4
          with:
            repository: "weinibuliu/Maa-Mirror-Secret"
            token: ${{ secrets.API_TOKEN_GITHUB }}
            path: secret

        - name: Download Release
          uses: robinraju/release-downloader@v1
          with:
            repository: "MaaAssistantArknights/MaaAssistantArknights"
            tag: ${{ needs.Build.outputs.ver }}
            out-file-path: "."
            fileName: "*"
            zipBall: true
            token: ${{ secrets.GITHUB_TOKEN }}

        - name: Setup Python
          uses: actions/setup-python@v5
          with:
            python-version: "3.12"

        - name: Install Deps
          run: |
            pip install -r requirements.txt
            sudo apt-get install p7zip-full

        - name: Run Check
          run: |
            python index.py --check --token ${{ secrets.GITHUB_TOKEN }}

        - name: Zip File
          run: |
            7z a -sfx MAA-${{ env.update_ver }}-win-x64.exe MAA-${{ env.update_ver }}-win-x64.zip

        - name: Run Upload
          timeout-minutes: 60
          run: |
            mv -f secret/.bypy .bypy
            mv -f .bypy /home/runner/.bypy
            sudo chmod 755 /home/runner/.bypy
            python index.py --upload --ali ${{ secrets.ALI_TOKEN }}
            mv -f /home/runner/.bypy .bypy

        - name: Run Issue
          run: |
            python index.py --issue --token ${{ secrets.API_TOKEN_GITHUB }}

        - name: Commit Secret
          uses: dmnemec/copy_file_to_another_repo_action@main
          env:
            API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
          with:
            source_file: '.bypy'
            destination_repo: 'weinibuliu/Maa-Mirror-Secret'
            destination_folder: "."
            user_email: 41898282+github-actions[bot]@users.noreply.github.com
            user_name: GitHub Actions
            commit_message: "[UPDATE] ${{ env.update_ver }}"

        - name: Commit Version
          uses: EndBug/add-and-commit@v9
          with:
            add: |
              version
            message: "[UPDATE] ${{ env.update_ver }}"
            default_author: github_actions
            committer_name: GitHub Actions
            committer_email: 41898282+github-actions[bot]@users.noreply.github.com