name: Check

on:
    workflow_call:

    workflow_dispatch:

    push:
      branches:
      - "**"

    schedule:
      - cron: "0/20 * * * *" # Runs every 20 minutes

jobs:
    run:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Code
          uses: actions/checkout@v4

        - name: Setup Python
          uses: actions/setup-python@v5
          with:
            python-version: "3.12"

        - name: Install Deps
          run: |
            pip install -r requirements.txt

        - name: Run check
          run: |
            python index.py --check --token ${{ secrets.GITHUB_TOKEN }}

        - name: Checkout Secret
          if: env.updatable == 'true'
          uses: actions/checkout@v4
          with:
            repository: "weinibuliu/Maa-Mirror-Secret"
            token: ${{ secrets.API_TOKEN_GITHUB }}
            path: secret

        - name: Download Release
          if: env.updatable == 'true'
          uses: robinraju/release-downloader@v1
          with:
            repository: "MaaAssistantArknights/MaaAssistantArknights"
            tag: ${{ env.ver }}
            out-file-path: "."
            fileName: "*"
            zipBall: true
            token: ${{ secrets.GITHUB_TOKEN }}

        - name: Zip File
          if: env.updatable == 'true'
          run: |
            sudo apt-get install p7zip-full
            7z a -sfx MAA-${{ env.ver }}-win-x64.exe MAA-${{ env.ver }}-win-x64.zip

        - name: Run Upload
          if: env.updatable == 'true'
          timeout-minutes: 60
          run: |
            mv -f secret/.bypy .bypy
            mv -f .bypy /home/runner/.bypy
            sudo chmod 755 /home/runner/.bypy
            python index.py --upload --ali ${{ secrets.ALI_TOKEN }}
            mv -f /home/runner/.bypy .bypy

        - name: Run Issue
          if: env.updatable == 'true'
          run: |
            python index.py --issue --token ${{ secrets.API_TOKEN_GITHUB }}

        - name: Commit Version
          if: env.updatable == 'true'
          uses: EndBug/add-and-commit@v9
          with:
            add: |
              version
            message: "[UPDATE] ${{ env.ver }}"
            default_author: github_actions
            committer_name: GitHub Actions
            committer_email: 41898282+github-actions[bot]@users.noreply.github.com